service: api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  stage: dev
  timeout: 15
  region: us-east-2

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      DB_CONNECTION_STRING: ${env:DB_CONNECTION_STRING}
      SECRET: ${env:SECRET}
      REFRESH_LIFE: ${env:REFRESH_LIFE}
      TRAINER_LIFE: ${env:TRAINER_LIFE}
      COOKIE: ${env:COOKIE}
      GROUPID: ${env:GROUPID}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env.${self:provider.stage}
    include:
      - DB_CONNECTION_STRING
      - SECRET
      - REFRESH_LIFE
      - TRAINER_LIFE
      - COOKIE
      - GROUPID

useDotenv: true